### ISSUE TITLE
au.camelcamelcamel.com support 

### ISSUE THREAD

**Issue by yerc** [ebaschiera/TripleCamel#12]
App says url not found.  I believe because I am from Australia, I use Amazon Australia and the Australia CamelCamelCamel site https://au.camelcamelcamel.com while your app could be checking the camelcamelcamel.com (without "au") in front). Wish there is an option in the app to choose the country specific site of CamelCamelCamel.

**Comment by ebaschiera** [comment]
Hi,
the app redirects to https://camelcamelcamel.com/search?sq=... then it's CamelCamelCamel who redirects to its localized website.
Is it CamelCamelCamel who is telling you that the URL is not found?

**Comment by yerc** [comment]
[Note - I edited my first post].  It's TripleCamel giving the message. To be more precise there's further content in that message saying TripleCamel will only work using an Amazon URL.  Further testing using Amazon websites (not Amazon app) shows that sharing from amazon.com works while sharing from amazon.com.au makes TripleCamel app show that error message. I also note that searching for an Amazon Australia listing in  camelcamelcamel.com (without the "au" in front) would not find the items meaning CamelCamelCamel itself could not redirect searches to the localised website. Therefore if TripleCamel has an option to set the localised CamelCamelCamel website then we could use TripleCamel for all Amazon websites.

**Comment by ebaschiera** [comment]
Thanks for the analysis!
It looks like TripleCamel is missing the AU support.
I did a check and noticed that many other countries are missing. I will add them.
Unfortunately CamelCamelCamel doesn't support all the countries that Amazon does, but I see no reason to block them on TripleCamel.

**Comment by ebaschiera** [comment]
Modification done!
Now we have just to wait for F-Droid to pick up the new version and release it.
Thanks!

**Comment by yerc** [comment]
Thank you for sharing your app.

I have updated the app to version 1.0.10.  It still does not work with Amazon Australia URL - same message as before. 

Would appreciate you taking another look.

Thanks,
Rey

**Comment by ebaschiera** [comment]
This bugfix is in 1.0.11.

It will take days (or a couple of weeks) for F-Droid to distribute it.
