### ISSUE TITLE
Error: "Sorry no suitable app found to open a URL"

### ISSUE THREAD

**Issue by bmbouter** [ebaschiera/TripleCamel#13]
I installed the app via Fdroid. I go to amazon and "share to TripleCamel" and I see the error message `Sorry no suitable app found to open a URL`. I suspect this isn't an issue with the app itself, but something with how my phone is configured. I have duckduckgo configured as my browser default on the phone and it's also installed via Fdroid so I'm not sure what I can do to resolve this.

Any advice on how to get this working?

This app looks great, I'm looking forward to using it.

**Comment by s1dh** [comment]
Same here with Android as default browser . Android 11.

**Comment by ebaschiera** [comment]
Thanks for reporting the issue!

The bug is fixed in version 1.0.12. We just have to wait a couple of days for F-Droid to pick it up and distribute it.

**Comment by bmbouter** [comment]
Awesome! Thanks!

**Comment by s1dh** [comment]
Thanks for your quick fix !

Regards,
