### ISSUE TITLE
Sorry, no Amazon link found.

### ISSUE THREAD

**Issue by Testorakel** [ebaschiera/TripleCamel#15]
I installed the latest version 1.0.13 from the F-Droid store and I get the following error message when I share a link from the Amazon app:

> Sorry, no Amazon link found. TripleCamel will work only sharing an Amazon URL.

Amazon: v24.11.0.100
Android: 12

**Comment by ebaschiera** [comment]
Hi @Poldi1977 , can you paste here one of those links so I can take a look, please?

**Comment by Testorakel** [comment]
I tried several links, but none worked. Here is one of the links:

`Grin&Bear Herren Hoodie Slim fit Kapuzenpullover Kapuzenjacke mit gestempeltem Design Logo GEC540 https://amzn.eu/d/2Euir6I`

**Comment by ebaschiera** [comment]
Yeah, I see. The app looks for a set of known domains (see https://github.com/ebaschiera/TripleCamel/blob/master/app/src/main/java/com/ebaschiera/triplecamel/ShareActivity.java#L32), and `amzn.eu` isn't in that set.
I'm going to add it.

Thanks.

**Comment by imlinstress** [comment]
We are waiting! ;)

Thanks for the usefull App.

**Comment by ebaschiera** [comment]
Fixed in https://github.com/ebaschiera/TripleCamel/commit/fe694d5c9c974f7d139d32d1777e1c36bfbabe00
Now we have to wait for F-Droid to distribute the new release (this can take several days)

**Comment by ebaschiera** [comment]
The fix will be in v1.0.14
