### ISSUE TITLE
App does not recognize a.co links

### ISSUE THREAD

**Issue by bwrsandman** [ebaschiera/TripleCamel#16]
Amazon Version 24.12.6.100
Triple Camel Version 1.0.15 

Shared text: Jim Shore Heartwood Creek Mini Stone Resin Camel Figurines Set of Two, 4.25” https://a.co/d/jhY0OXA

**Comment by slimninja** [comment]
@ebaschiera similar issue, please take a look when you can

**Comment by ebaschiera** [comment]
Fixed with https://github.com/ebaschiera/TripleCamel/commit/b608c23258bfe3f9984c1f6c4efe5384a68c1b50
Tagged version 1.0.16 just now, so we have to wait for F-Droid to pick it up and distribute it.

Thanks for reporting the issue!

**Comment by slimninja** [comment]
Thanks @ebaschiera . How long does that generally take to propagate? I can only see a .15 on the GitHub releases as well

**Comment by ebaschiera** [comment]
I created a release in Github (thanks for pointing it out), but that's not a blocker for F-Droid distribution. In fact, I can see the newest version here: https://f-droid.org/packages/com.ebaschiera.triplecamel/ 
You should now be able to get it from F-Droid on your device.

**Comment by slimninja** [comment]
> I created a release in Github (thanks for pointing it out), but that's not a blocker for F-Droid distribution. In fact, I can see the newest version here: https://f-droid.org/packages/com.ebaschiera.triplecamel/ 
> You should now be able to get it from F-Droid on your device.
> 

Wonderful. I can see it now. Checked this morn and it wasn't there either. 

Much appreciated!
