### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by war59312** [ebaschiera/TripleCamel#6]
How to use?

Really need to supply some directions.

Thanks

**Comment by ebaschiera** [comment]
Hi,
I will try to be more clear in the readme in next release.
Anyway, you just have to browse the products you are interested in on the Amazon app. Then click on "Share" in the product page and then select TripleCamel as the app to share to.
It's just that.

**Comment by war59312** [comment]
Got it, thank you.

Working great. :)
