### ISSUE TITLE
smile.amazon.com support? 

### ISSUE THREAD

**Issue by smikwily** [ebaschiera/TripleCamel#7]
Any chance you could add support for Amazon Smile? I believe it is just a subdomain format on Amazon, but your plugin doesn't like the URL format. 

Thanks!

**Comment by ebaschiera** [comment]
Hi,
I am trying to figure out how to get to Amazon Smile on the Amazon app... Does the Amazon app support Smile?

**Comment by smikwily** [comment]
I don't believe so. I think the only way to access it is by going to http://smile.amazon.com . I think your app would be fine if it either stripped the smile bit off or accepted it as being a valid url. The CCC website appears to accept the urls, but linking back via the "buy" button does not point to the smile url, which isn't a huge deal, at least for me.

**Comment by oiisamiio** [comment]
Hi there.
Amazon App Supports actually AmazonSmile and produce “Sorry no Amazon link found“

**Comment by ebaschiera** [comment]
This bugifx/new feature is in 1.0.9 👍

**Comment by oiisamiio** [comment]
Special thanks ;)
